backend:
  name: github
  repo: andrew-braun/geobeermap

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    extension: mdx
    format: frontmatter
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: date,
          label: Date,
          widget: datetime,
          default: "",
          date_format: "MMMM DD, YYYY",
          format: "MMMM DD, YYYY",
        }
      - { name: title, label: Title }
      - {
          name: images,
          label: Images,
          widget: image,
          allow_multiple: true,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
  - name: entries
    label: Entries
    folder: entries
    extension: "mdx"
    format: frontmatter
    create: true
    fields:
      - {
          name: date,
          label: Entry Publication Date,
          widget: datetime,
          default: "",
          date_format: "MMMM DD, YYYY",
          format: "MMMM DD, YYYY HH:mm",
        }
      - { name: name, label: Business Name }
      - {
          name: type,
          label: Business Type,
          widget: select,
          multiple: true,
          options: ["Brewery", "Bar", "Retailer", "Other"],
          default: ["Brewery"],
        }
      - {
          name: open,
          label: "Currently Operating",
          widget: boolean,
          default: true,
        }
      - { name: address, label: Address, required: false }
      - { name: city, label: City, required: false }
      - { name: country, label: Country, required: false }
      - { name: coordinates, label: Coordinates, required: false }
      - {
          name: openingdate,
          label: Opening Date,
          widget: datetime,
          default: "",
          date_format: "MMMM DD, YYYY",
          format: "MMMM DD, YYYY",
          required: false,
        }
      - {
          name: images,
          label: Images,
          widget: image,
          allow_multiple: true,
          required: false,
        }
      - {
          name: logo,
          label: Logo,
          widget: image,
          allow_multiple: false,
          required: false,
        }
      - { name: body, label: Description, widget: markdown, required: false }
      - { name: beers, label: Beers, widget: list, required: false }
      - {
          name: locations,
          label: "Where to Drink",
          widget: markdown,
          required: false,
        }
      - { name: website, label: Website, required: false }
      - { name: googlemaps, label: "Google Maps", required: false }
      - { name: facebook, label: Facebook, required: false }
      - { name: instagram, label: Instagram, required: false }
      - { name: twitter, label: Twitter, required: false }
      - { name: untappd, label: Untappd, required: false }
      - { name: path, label: Path }
      - { name: title, label: File Name }
